checks:
    php: true
filter: {  }
build:
    environment:
        php: '7.3'
    cache:
        directories:
            - vendor/
            - ~/.composer/cache/files
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=coverage'
                coverage:
                    file: 'coverage'
                    format: 'clover'
